### PR TITLE
Add slash commands and other various changes from devel

### PR DESCRIPTION
**Pull request by RedsTom**
Added :
 - slash command support
 
Updated : 
 - the JDA version
 - some messages

Removed : 
 - old commands
 - the help command

### CODE REVIEW

**Comment by RedsTom** [comment]
Note : forgot to test file upload as it changed, not merging atm

**Comment by RedsTom** [comment]
Problem fixed

**Review by g-clems — DISMISSED** [review]

**Review by g-clems — DISMISSED** [review]

**Review by g-clems — DISMISSED** [review]

**Review by AntoineJT — CHANGES_REQUESTED** [review]
I don't like the change from google java format to palantir because the argument is just week (see discussion on discord)

At least freeze the palantir version in the gradle build file, as for the google java format before

**Review by AntoineJT — APPROVED** [review]
let's use your heretic thing palantir

**Review by g-clems — APPROVED** [review]

**Pull request merged**
